let saved=JSON.parse(localStorage.getItem('challengeArenaUser')||'null')||{};
let score=Number(saved.score)||0,streak=Number(saved.streak)||0,best=Number(saved.best)||0,totalCorrect=Number(saved.totalCorrect)||0;
let authMode='signin',currentUser=null,dailyChallenge=null;
const supabaseClient=window.challengeArenaSupabase;
const bank={quiz:[['Which planet is known as the Red Planet?',['Venus','Mars','Jupiter','Mercury'],1],['Which is the largest ocean?',['Atlantic','Indian','Pacific','Arctic'],2],['How many sides does a hexagon have?',['5','6','7','8'],1],['What is 12 × 8?',['86','96','108','112'],1],['Which gas do plants absorb?',['Oxygen','Nitrogen','Carbon dioxide','Helium'],2]],mystery:[['I have a face and two hands but no arms or legs. What am I?',['A clock','A robot','A statue','A mirror'],0],['What gets wetter as it dries?',['A towel','A cloud','A sponge','Rain'],0],['What has many teeth but cannot bite?',['A comb','A shark','A saw','A zipper'],0],['What can travel around the world while staying in a corner?',['A stamp','A map','A coin','A letter'],0]],riddle:[['What has keys but cannot open a lock?',['A map','A piano','A clock','A river'],1],['What has a neck but no head?',['A shirt','A bottle','A tree','A shoe'],1],['What has words but never speaks?',['A book','A phone','A radio','A teacher'],0],['What belongs to you but other people use it more than you?',['Your name','Your phone','Your car','Your house'],0]],speed:[['Which number comes next: 2, 4, 6, 8, ?',['9','10','11','12'],1],['Which is the fastest land animal?',['Lion','Horse','Cheetah','Tiger'],2],['How many days are in a leap year?',['364','365','366','367'],2],['Which shape has three sides?',['Square','Circle','Triangle','Hexagon'],2]]};
let mode='quiz',questions=[],qi=0,roundCorrect=0,roundScore=0,timer=null,timeLeft=0,answered=false;
function save(){localStorage.setItem('challengeArenaUser',JSON.stringify({name:saved.name||'',score,streak,best,totalCorrect,updatedAt:new Date().toISOString()}));}
function refreshStats(){document.getElementById('points').textContent=score;document.getElementById('streak').textContent=streak;document.getElementById('best').textContent=best;const you=document.getElementById('youScore');if(you)you.textContent=score+' pts';renderBadges();}
function todayKey(){return new Date().toISOString().slice(0,10)}
async function loadDailyChallenge(){if(!supabaseClient)return false;try{const {data,error}=await supabaseClient.rpc('get_daily_challenge');if(error){console.warn('Daily challenge sync failed:',error.message);return false;}if(data&&data.date===todayKey()&&Array.isArray(data.questions)&&data.questions.length){dailyChallenge=data;return true;}return false;}catch(e){console.warn('Daily challenge load failed:',e);return false;}}
async function startChallenge(){if(!dailyChallenge||dailyChallenge.date!==todayKey())await loadDailyChallenge();play('quiz',true)}
function play(type='quiz',daily=false){mode=type;if(daily&&dailyChallenge&&dailyChallenge.date===todayKey()&&Array.isArray(dailyChallenge.questions)){questions=dailyChallenge.questions.map(q=>[q.question,q.options,q.answer]).filter(q=>q[0]&&Array.isArray(q[1])&&q[1].length&&Number.isInteger(q[2]));}else{questions=[...(bank[type]||bank.quiz)];if(daily){const seed=[...todayKey()].reduce((a,c)=>a+c.charCodeAt(0),0);const n=seed%questions.length;questions=[...questions.slice(n),...questions.slice(0,n)];}}if(!questions.length){questions=[...bank.quiz];}else if(!daily)questions.sort(()=>Math.random()-.5);questions=questions.slice(0,Math.min(5,questions.length));qi=0;roundCorrect=0;roundScore=0;document.getElementById('gameTitle').textContent=daily?'🔥 Daily Challenge':({quiz:'🧠 Brain Quiz',mystery:'🕵️ Mystery',riddle:'🧩 Riddle',speed:'⚡ Speed Challenge'}[type]||'Challenge');document.getElementById('game').classList.remove('hidden');render();}
function render(){clearInterval(timer);answered=false;const x=questions[qi];document.getElementById('gameProgress').textContent=`Question ${qi+1} of ${questions.length}`;document.getElementById('question').textContent=x[0];document.getElementById('answers').innerHTML=x[1].map((v,i)=>`<button class="answer" onclick="answer(${i})">${v}</button>`).join('');document.getElementById('feedback').textContent='';document.getElementById('nextBtn').classList.add('hidden');if(mode==='speed'){timeLeft=60;document.getElementById('timer').textContent='⏱️ 60s';timer=setInterval(()=>{timeLeft--;document.getElementById('timer').textContent='⏱️ '+timeLeft+'s';if(timeLeft<=0){clearInterval(timer);answer(-1);}},1000)}else document.getElementById('timer').textContent='';}
function answer(i){if(answered)return;answered=true;clearInterval(timer);const x=questions[qi];document.querySelectorAll('.answer').forEach(b=>b.disabled=true);const correct=i===x[2];if(correct){const pts=mode==='speed'?150:100;score+=pts;roundScore+=pts;roundCorrect++;totalCorrect++;document.getElementById('feedback').textContent=`✅ Correct! +${pts} points`;}else document.getElementById('feedback').textContent=i===-1?'⏰ Time up!':'❌ Not quite. The correct answer was '+x[1][x[2]]+'.';best=Math.max(best,roundScore);save();refreshStats();document.getElementById('nextBtn').textContent=qi===questions.length-1?'See Results →':'Next →';document.getElementById('nextBtn').classList.remove('hidden');}
function nextQuestion(){if(qi<questions.length-1){qi++;render();}else finishRound();}
async function ensureCloudProfile(){if(!supabaseClient||!currentUser)return;const name=(saved.name||currentUser.user_metadata?.display_name||'').trim();const {error}=await supabaseClient.from('profiles').upsert({id:currentUser.id,display_name:name||null,updated_at:new Date().toISOString()},{onConflict:'id'});if(error)console.warn('Profile sync failed:',error.message);}
async function loadCloudStats(){if(!supabaseClient||!currentUser)return;const {data,error}=await supabaseClient.from('game_attempts').select('score,correct_answers').eq('user_id',currentUser.id);if(error){console.warn('Stats sync failed:',error.message);return;}const cloudScore=(data||[]).reduce((sum,row)=>sum+Number(row.score||0),0);const cloudCorrect=(data||[]).reduce((sum,row)=>sum+Number(row.correct_answers||0),0);if(cloudScore>score)score=cloudScore;if(cloudCorrect>totalCorrect)totalCorrect=cloudCorrect;best=Math.max(best,score);save();refreshStats();}
async function saveCloudAttempt(){if(!supabaseClient||!currentUser)return;const {error}=await supabaseClient.from('game_attempts').insert({user_id:currentUser.id,category:mode,score:roundScore,correct_answers:roundCorrect,total_questions:questions.length});if(error)console.warn('Attempt sync failed:',error.message);}
async function saveExternalAttempt(points,correct,total,category){if(!supabaseClient||!currentUser)return;const {error}=await supabaseClient.from('game_attempts').insert({user_id:currentUser.id,category,score:Number(points)||0,correct_answers:Number(correct)||0,total_questions:Number(total)||0});if(error)console.warn('External attempt sync failed:',error.message);}
function recordExternalScore(points,correct,total,category='ai'){score+=Number(points)||0;best=Math.max(best,score);totalCorrect+=Number(correct)||0;save();refreshStats();if(currentUser)saveExternalAttempt(points,correct,total,category);loadLeaderboard();}
window.challengeArenaCurrentUser=null;
window.challengeArenaRecordExternalScore=recordExternalScore;
async function loadLeaderboard(){const el=document.getElementById('leaderboardRows');if(!el||!supabaseClient)return;const {data,error}=await supabaseClient.rpc('get_leaderboard',{limit_count:10});if(error){el.innerHTML='<div class="row"><b>Leaderboard unavailable</b><span>Try again later</span></div>';console.warn('Leaderboard sync failed:',error.message);return;}if(!data||!data.length){el.innerHTML='<div class="row"><b>No scores yet</b><span>Be the first!</span></div>';return;}el.innerHTML=data.map((row,i)=>{const medal=i===0?'🥇':i===1?'🥈':i===2?'🥉':`${i+1}.`;const name=String(row.display_name||'Player').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));return `<div class="row"><b>${medal} ${name}</b><span>${Number(row.score||0)} pts</span></div>`;}).join('');}
function finishRound(){clearInterval(timer);const dailyDone=localStorage.getItem('challengeArenaDaily')===todayKey();if(!dailyDone){streak++;localStorage.setItem('challengeArenaDaily',todayKey());}best=Math.max(best,roundScore);save();refreshStats();if(currentUser)saveCloudAttempt();loadLeaderboard();document.getElementById('game').classList.add('hidden');document.getElementById('resultText').textContent=`You scored ${roundScore} points and got ${roundCorrect}/${questions.length} correct.`;document.getElementById('resultStats').innerHTML=`<p>🏆 Total points: <b>${score}</b></p><p>🔥 Streak: <b>${streak} day${streak===1?'':'s'}</b></p>`;document.getElementById('results').classList.remove('hidden');}
window.addEventListener('arenaRushFinished',e=>{const gained=Number(e.detail?.score)||0;score+=gained;best=Math.max(best,score);save();refreshStats();});
function closeGame(){clearInterval(timer);document.getElementById('game').classList.add('hidden')}function closeResults(){document.getElementById('results').classList.add('hidden')}
function openAuth(){document.getElementById('auth').classList.remove('hidden');updateAuthUI();}
function closeAuth(){document.getElementById('auth').classList.add('hidden')}
function toggleAuthMode(){authMode=authMode==='signin'?'signup':'signin';updateAuthUI();}
function updateAuthUI(){const signed=!!currentUser;document.getElementById('authTitle').textContent=signed?'👤 Your Account':authMode==='signin'?'👤 Sign in to Challenge Arena':'👤 Create Challenge Arena Account';document.getElementById('authMessage').textContent=signed?'You are signed in. Your progress is synced to your Challenge Arena account.':'Use your email and password to access your Challenge Arena account.';document.getElementById('authEmail').classList.toggle('hidden',signed);document.getElementById('authPassword').classList.toggle('hidden',signed);document.getElementById('userName').classList.toggle('hidden',signed);document.getElementById('authAction').classList.toggle('hidden',signed);document.getElementById('authSwitch').classList.toggle('hidden',signed);document.getElementById('logoutBtn').classList.toggle('hidden',!signed);if(!signed){document.getElementById('authAction').textContent=authMode==='signin'?'Sign in':'Create account';document.getElementById('authSwitch').textContent=authMode==='signin'?'Need an account? Sign up':'Already have an account? Sign in';}}
async function submitAuth(){const email=document.getElementById('authEmail').value.trim();const password=document.getElementById('authPassword').value;if(!email||password.length<6){document.getElementById('profileStatus').textContent='⚠️ Enter a valid email and a password of at least 6 characters.';return;}document.getElementById('authAction').disabled=true;document.getElementById('profileStatus').textContent='Please wait…';try{if(authMode==='signup'){const name=document.getElementById('userName').value.trim();const {data,error}=await supabaseClient.auth.signUp({email,password,options:{data:{display_name:name},emailRedirectTo:'https://mirzakashif434-source.github.io/Challenge-Arena/'}});if(error)throw error;if(data.session){currentUser=data.user;window.challengeArenaCurrentUser=currentUser;saved.name=name||saved.name||'';save();await ensureCloudProfile();await loadCloudStats();loadLeaderboard();document.getElementById('profileStatus').textContent='✅ Account created and signed in.';}else document.getElementById('profileStatus').textContent='✅ Account created. Check your email to confirm your account, then sign in.';}else{const {data,error}=await supabaseClient.auth.signInWithPassword({email,password});if(error)throw error;currentUser=data.user;window.challengeArenaCurrentUser=currentUser;await ensureCloudProfile();await loadCloudStats();loadLeaderboard();document.getElementById('profileStatus').textContent='✅ Signed in successfully.';}updateAuthUI();}catch(e){document.getElementById('profileStatus').textContent='❌ '+(e.message||'Authentication failed.');}finally{document.getElementById('authAction').disabled=false;}}
async function logout(){await supabaseClient.auth.signOut();currentUser=null;window.challengeArenaCurrentUser=null;updateAuthUI();document.getElementById('profileStatus').textContent='Signed out.';loadLeaderboard();}
function saveProfile(){const name=document.getElementById('userName').value.trim();if(!name)return;saved.name=name;save();document.getElementById('profileStatus').textContent='✅ Profile saved on this device.';if(currentUser)ensureCloudProfile();}
function resetProfile(){if(confirm('Reset your local Challenge Arena profile and score?')){localStorage.removeItem('challengeArenaUser');localStorage.removeItem('challengeArenaDaily');location.reload()}}
function openPremium(){document.getElementById('premium').classList.remove('hidden')}function closePremium(){document.getElementById('premium').classList.add('hidden')}
function renderBadges(){const el=document.getElementById('badges');if(!el)return;const b=[];if(totalCorrect>=1)b.push('🎯 First Win');if(totalCorrect>=10)b.push('🏅 10 Correct');if(score>=500)b.push('⭐ 500 Points');if(streak>=3)b.push('🔥 3-Day Streak');el.textContent=b.length?b.join('  ·  '):'Complete challenges to earn badges.'}
supabaseClient.auth.getSession().then(({data})=>{currentUser=data.session?.user||null;window.challengeArenaCurrentUser=currentUser;if(currentUser){ensureCloudProfile();loadCloudStats();}loadLeaderboard();loadDailyChallenge();}).catch(()=>{loadLeaderboard();loadDailyChallenge();});
supabaseClient.auth.onAuthStateChange((_event,session)=>{currentUser=session?.user||null;window.challengeArenaCurrentUser=currentUser;if(currentUser){ensureCloudProfile();loadCloudStats();}loadLeaderboard();if(document.getElementById('auth')&&!document.getElementById('auth').classList.contains('hidden'))updateAuthUI();});
refreshStats();loadLeaderboard();loadDailyChallenge();